export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";

export const MEASUREMENTS_REQUEST = "MEASUREMENTS_REQUEST";
export const MEASUREMENTS_SUCCESS = "MEASUREMENTS_SUCCESS";
export const MEASUREMENTS_FAILURE = "MEASUREMENTS_FAILURE";

export const MEASUREMENTS_CREATE_REQUEST = "MEASUREMENTS_CREATE_REQUEST";
export const MEASUREMENTS_CREATE_SUCCESS = "MEASUREMENTS_CREATE_SUCCESS";
export const MEASUREMENTS_CREATE_FAILURE = "MEASUREMENTS_CREATE_FAILURE";

export const MEASUREMENTS_UPDATE_REQUEST = "MEASUREMENTS_UPDATE_REQUEST";
export const MEASUREMENTS_UPDATE_SUCCESS = "MEASUREMENTS_UPDATE_SUCCESS";
export const MEASUREMENTS_UPDATE_FAILURE = "MEASUREMENTS_UPDATE_FAILURE";

export const MEASUREMENTS_REMOVE_REQUEST = "MEASUREMENTS_REMOVE_REQUEST";
export const MEASUREMENTS_REMOVE_SUCCESS = "MEASUREMENTS_REMOVE_SUCCESS";
export const MEASUREMENTS_REMOVE_FAILURE = "MEASUREMENTS_REMOVE_FAILURE";
